- hosts: localhost
  become_user: root
  tasks:
    - name: include variables
      include_vars: /home/ec2-user/ansibleproj/vars/vpc_setup
    - name: install vpc
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpc_Cidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout
    - name: Create a public subnet with zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub1Cidr}}"
        az: "{{zone1}}"
        map_public: yes
        state: present
        resource_tags:
          Name: vprofile-pubsub1
      register: pubsub1
    - name: Create a public subnet with zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub2Cidr}}"
        az: "{{zone2}}"
        map_public: yes
        state: present
        resource_tags:
         Name: vprofile-pubsub2
      register: pubsub2
    - name: Create a public subnet with zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PubSub3Cidr}}"
        az: "{{zone3}}"
        map_public: yes
        state: present
        resource_tags:
         Name: vprofile-pubsub3
      register: pubsub3
    - name: Create a private subnet with zone 1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub1Cidr}}"
        az: "{{zone1}}"
        map_public: yes
        state: present
        resource_tags:
         Name: vprofile-privsub1
      register: privsub1
    - name: Create a private subnet with zone 2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub2Cidr}}"
        az: "{{zone2}}"
        map_public: yes
        state: present
        resource_tags: 
         Name: vprofile-privsub2
      register: privsub2
    - name: Create a private subnet with zone 3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        cidr: "{{PrivSub3Cidr}}"
        az: "{{zone3}}"
        map_public: yes
        state: present
        resource_tags:
         Name: vprofile-privsub3
      register: privsub3
    - name: Internet Gateway setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        resource_tags:
         Name: vprofile_IGW
      register: igw_out
    - name: Create a route table
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: VProfile-PuRT 
        subnets:
          - "{{pubsub1.subnet.id}}"
          - "{{pubsub2.subnet.id}}"
          - "{{pubsub3.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw_out.gateway_id}}"
      register: pubRT_out
    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1.subnet.id
        - pubsub2.subnet.id
        - pubsub3.subnet.id
        - privsub1.subnet.id
        - privsub2.subnet.id
        - privsub3.subnet.id
        - igw_out.gateway_id
        - pubRT_out.route_table.id
    - set_fact:
        vpc_id: "{{ vpcout.vpc.id}}"    
        pubsub1id: "{{ pubsub1.subnet.id}}"
        pubsub2id: "{{ pubsub3.subnet.id}}"
        pubsub3id: "{{ pubsub3.subnet.id}}"
        privsub1id: "{{privsub1.subnet.id}}"
        privsub2id: "{{privsub2.subnet.id}}"
        privsub3id: "{{privsub3.subnet.id}}"
        igwid: "{{igw_out.gateway_id}}"
        pubRTid: "{{ pubRT_out.route_table.id}}"
        cacheable: yes

    - name: Create a var file for VPC
      copy:
        content: "region: {{region}}\n vpc_id: {{ vpcout.vpc.id}}\n pubsub1id: {{ pubsub1.subnet.id}}\n pubsub2id: {{ pubsub3.subnet.id}}\n pubsub3id: {{ pubsub3.subnet.id}}\n  privsub1id: {{privsub1.subnet.id}}\n privsub2id: {{privsub2.subnet.id}}\n  privsub3id: {{privsub3.subnet.id}}\n igwid: {{igw_out.gateway_id}}\n pubRTid: {{ pubRT_out.route_table.id}}"
        dest: vars/output_var

